"""empty message

Revision ID: 01b069dbb3e2
Revises: b2e8eaca7899
Create Date: 2024-04-01 20:41:21.445783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b069dbb3e2'
down_revision: Union[str, None] = 'b2e8eaca7899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('blind_date', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('blind_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'blind_date')
    op.drop_column('comment', 'blind_date')
    # ### end Alembic commands ###
