"""empty message

Revision ID: 0227f87dc8a3
Revises: 6b1db996a77e
Create Date: 2024-03-26 03:42:42.070796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0227f87dc8a3'
down_revision: Union[str, None] = '6b1db996a77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accompany', sa.Column('report_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('notice', sa.Column('report_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'report_count')
    op.drop_column('accompany', 'report_count')
    # ### end Alembic commands ###
