"""empty message

Revision ID: 0c49f7ca9ee8
Revises: a1affe6dfdc5
Create Date: 2024-02-15 10:47:27.666610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c49f7ca9ee8'
down_revision: Union[str, None] = 'a1affe6dfdc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
