"""empty message

Revision ID: 1549264ee9dc
Revises: 6ba69d8ccb37
Create Date: 2024-05-21 02:13:51.667764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1549264ee9dc'
down_revision: Union[str, None] = '6ba69d8ccb37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_notice_user_id'), 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notice_user_id'), type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
