"""empty message

Revision ID: 194a9c0f7069
Revises: ab06c0131e15
Create Date: 2024-06-11 16:50:35.083160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194a9c0f7069'
down_revision: Union[str, None] = 'ab06c0131e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deletion_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deletion_date')
    # ### end Alembic commands ###
