"""empty message

Revision ID: 1c5a121bc0fd
Revises: df04aa24c18d
Create Date: 2024-02-14 18:22:07.786028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5a121bc0fd'
down_revision: Union[str, None] = 'df04aa24c18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'content_img')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content_img', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
