"""empty message

Revision ID: 2ff28d8f5eae
Revises: 771b7992627d
Create Date: 2024-04-06 18:26:28.608990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff28d8f5eae'
down_revision: Union[str, None] = '771b7992627d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('report_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'report_date')
    # ### end Alembic commands ###
