"""empty message

Revision ID: 36f4536e591d
Revises: 421c462d00c4
Create Date: 2024-02-11 00:46:29.334453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f4536e591d'
down_revision: Union[str, None] = '421c462d00c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('create_date', sa.DateTime(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'create_date')
    # ### end Alembic commands ###
