"""empty message

Revision ID: 37b80c7534f6
Revises: 3cd700213d00
Create Date: 2024-02-17 05:10:58.373173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b80c7534f6'
down_revision: Union[str, None] = '3cd700213d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('image_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'image_hash')
    # ### end Alembic commands ###
