"""empty message

Revision ID: 3a86556b2cfb
Revises: 8b8d812d7b98
Create Date: 2024-03-03 01:33:08.163707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a86556b2cfb'
down_revision: Union[str, None] = '8b8d812d7b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accompany', sa.Column('qna', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accompany', 'qna')
    # ### end Alembic commands ###
