"""empty message

Revision ID: 522e0fa29d81
Revises: 48aa2a47222b
Create Date: 2024-06-14 18:51:46.536126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522e0fa29d81'
down_revision: Union[str, None] = '48aa2a47222b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insight', sa.Column('language', sa.Enum('korean', 'english', name='languagecategory'), nullable=False,
                                       server_default='korean'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insight', 'language')
    # ### end Alembic commands ###
