"""empty message

Revision ID: 59aed4abda9f
Revises: 58cfd4515e6a
Create Date: 2024-02-10 01:17:16.782267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59aed4abda9f'
down_revision: Union[str, None] = '58cfd4515e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('modify_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'modify_date')
    # ### end Alembic commands ###
