"""empty message

Revision ID: 5f7f4c10cdeb
Revises: b22e3af2b491
Create Date: 2024-06-03 18:31:49.347981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7f4c10cdeb'
down_revision: Union[str, None] = 'b22e3af2b491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('noti_activity', sa.Boolean(), nullable=False),
    sa.Column('noti_chat', sa.Boolean(), nullable=False),
    sa.Column('noti_marketing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_setting')
    # ### end Alembic commands ###
