"""empty message

Revision ID: 6aea49037f2d
Revises: 0c49f7ca9ee8
Create Date: 2024-02-15 11:14:19.807972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aea49037f2d'
down_revision: Union[str, None] = '0c49f7ca9ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('create_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'create_date')
    # ### end Alembic commands ###
