"""empty message

Revision ID: 6da31da4400c
Revises: 9d00a2010229
Create Date: 2024-05-27 16:44:17.993225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da31da4400c'
down_revision: Union[str, None] = '9d00a2010229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insight', sa.Column('create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insight', 'create_date')
    # ### end Alembic commands ###
