"""empty message

Revision ID: 6fd40ab5dd0f
Revises: 026a806a7fcf
Create Date: 2024-01-31 21:49:54.756570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd40ab5dd0f'
down_revision: Union[str, None] = '026a806a7fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'like_count')
    # ### end Alembic commands ###
