"""empty message

Revision ID: 771b7992627d
Revises: 735595bee7c7
Create Date: 2024-04-04 19:33:17.913861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771b7992627d'
down_revision: Union[str, None] = '735595bee7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accompany', sa.Column('is_blinded', sa.Boolean(), nullable=False))
    op.add_column('notice', sa.Column('is_blinded', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'is_blinded')
    op.drop_column('accompany', 'is_blinded')
    # ### end Alembic commands ###
