"""empty message

Revision ID: 78280ccd6797
Revises: 9bfc19fd5310
Create Date: 2024-04-22 17:46:07.967099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78280ccd6797'
down_revision: Union[str, None] = '9bfc19fd5310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('sender_firebase_uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'sender_firebase_uuid')
    # ### end Alembic commands ###
