"""empty message

Revision ID: 86a04a7f67e3
Revises: c154d122b255
Create Date: 2024-02-16 02:03:28.999403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a04a7f67e3'
down_revision: Union[str, None] = 'c154d122b255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('update_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'update_date')
    # ### end Alembic commands ###
