"""empty message

Revision ID: 8b8d812d7b98
Revises: f4225d965f20
Create Date: 2024-02-29 03:33:26.519566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8d812d7b98'
down_revision: Union[str, None] = 'f4225d965f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accompany', sa.Column('is_closed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accompany', 'is_closed')
    # ### end Alembic commands ###
