"""empty message

Revision ID: a5ec19870a1d
Revises: 78c66383becf
Create Date: 2024-03-31 16:31:47.192495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ec19870a1d'
down_revision: Union[str, None] = '78c66383becf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('is_blinded', sa.Boolean(), nullable=False, server_default=sa.text('False')))
    op.add_column('post', sa.Column('is_blinded', sa.Boolean(), nullable=False, server_default=sa.text('False')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_blinded')
    op.drop_column('comment', 'is_blinded')
    # ### end Alembic commands ###
