"""empty message

Revision ID: a88fbf38e42f
Revises: 0079cecf7fbe
Create Date: 2024-03-08 17:28:02.175775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88fbf38e42f'
down_revision: Union[str, None] = '0079cecf7fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_nickname_change', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('suspension_period', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'suspension_period')
    op.drop_column('user', 'last_nickname_change')
    # ### end Alembic commands ###
