"""empty message

Revision ID: ab9aa9c8e6d3
Revises: 0227f87dc8a3
Create Date: 2024-03-27 18:27:32.134501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9aa9c8e6d3'
down_revision: Union[str, None] = '0227f87dc8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firebase_uuid', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'firebase_uuid')
    # ### end Alembic commands ###
