"""empty message

Revision ID: b22e3af2b491
Revises: 6da31da4400c
Create Date: 2024-06-03 15:12:52.701487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22e3af2b491'
down_revision: Union[str, None] = '6da31da4400c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insight', sa.Column('main_image', sa.String(), nullable=True))
    op.add_column('insight', sa.Column('category', sa.String(), nullable=False, server_default='유용한 정보'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insight', 'category')
    op.drop_column('insight', 'main_image')
    # ### end Alembic commands ###
