"""empty message

Revision ID: be2f9da12ed8
Revises: aaec3f206f22
Create Date: 2024-03-03 05:35:20.355841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2f9da12ed8'
down_revision: Union[str, None] = 'aaec3f206f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('answer', sa.String(), nullable=False))
    op.add_column('application', sa.Column('apply_date', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'apply_date')
    op.drop_column('application', 'answer')
    # ### end Alembic commands ###
