"""empty message

Revision ID: e601de43a283
Revises: 9f404fc41876
Create Date: 2024-05-04 16:36:23.840782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e601de43a283'
down_revision: Union[str, None] = '9f404fc41876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment") as batch_op:
        batch_op.add_column(sa.Column('vocabulary_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_comment_vocabulary', 'vocabulary', ['vocabulary_id'], ['id'])

    op.create_table(
        'vocabulary',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('subject', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('is_solved', sa.Boolean(), nullable=False),
        sa.Column('report_count', sa.Integer(), nullable=False),
        sa.Column('create_date', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('solved_user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['solved_user_id'], ['user.id'], name='fk_vocabulary_solved_user'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_vocabulary_user'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment") as batch_op:
        batch_op.drop_constraint('fk_comment_vocabulary', type_='foreignkey')
        batch_op.drop_column('vocabulary_id')

    op.drop_table('vocabulary')
    # ### end Alembic commands ###