"""empty message

Revision ID: e659524ee7f9
Revises: 90c4d0e663dd
Create Date: 2024-04-07 20:08:46.339785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e659524ee7f9'
down_revision: Union[str, None] = '90c4d0e663dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('blind_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'blind_date')
    # ### end Alembic commands ###
