"""empty message

Revision ID: ee89655c6b9b
Revises: 28c58312764d
Create Date: 2024-02-10 01:50:51.700787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee89655c6b9b'
down_revision: Union[str, None] = '28c58312764d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('is_anonymous', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'is_anonymous')
    # ### end Alembic commands ###
